// ─── Products ────────────────────────────────────────────────────────────────

export const PRODUCTS = [
  {
    id: 1,
    name: 'AuraLamp Pro',
    price: 49.99,
    originalPrice: 89.99,
    category: 'Home',
    badge: 'Best Seller',
    description: 'Smart ambient LED lamp with 16M colors and app control. Set the mood for any room.',
    features: ['16 million colors', 'App controlled', 'Voice assistant compatible', 'Timer & scheduling'],
    emoji: '💡',
    gradient: 'linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)',
    rating: 4.9,
    reviews: 2847,
  },
  {
    id: 2,
    name: 'ZenBrew Portable',
    price: 34.99,
    originalPrice: 59.99,
    category: 'Kitchen',
    badge: 'Trending',
    description: 'USB-C rechargeable coffee maker. Brew anywhere in 3 minutes flat.',
    features: ['USB-C charging', '3 min brew time', '12oz capacity', 'Travel-friendly'],
    emoji: '☕',
    gradient: 'linear-gradient(135deg, #a18cd1 0%, #fbc2eb 100%)',
    rating: 4.7,
    reviews: 1923,
  },
  {
    id: 3,
    name: 'CloudRest Pillow',
    price: 29.99,
    originalPrice: 54.99,
    category: 'Bedroom',
    badge: 'New',
    description: 'Memory foam cervical pillow with cooling gel technology for deep sleep.',
    features: ['Cooling gel layer', 'Ergonomic contour', 'Hypoallergenic', 'Machine washable cover'],
    emoji: '☁️',
    gradient: 'linear-gradient(135deg, #c3cfe2 0%, #f5f7fa 100%)',
    rating: 4.8,
    reviews: 3201,
  },
  {
    id: 4,
    name: 'SnapClean Mini',
    price: 24.99,
    originalPrice: 44.99,
    category: 'Tech',
    badge: 'Hot Deal',
    description: 'Portable UV-C sanitizer for phones, keys, and accessories. 99.9% germ-free.',
    features: ['UV-C technology', '99.9% sanitization', 'Compact design', 'USB rechargeable'],
    emoji: '✨',
    gradient: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    rating: 4.6,
    reviews: 1456,
  },
  {
    id: 5,
    name: 'FlexDesk Stand',
    price: 39.99,
    originalPrice: 69.99,
    category: 'Office',
    badge: 'Popular',
    description: 'Adjustable aluminum laptop stand with built-in cable management.',
    features: ['6 height levels', 'Cable management', 'Aluminum alloy', 'Foldable design'],
    emoji: '💻',
    gradient: 'linear-gradient(135deg, #89f7fe 0%, #66a6ff 100%)',
    rating: 4.8,
    reviews: 2156,
  },
  {
    id: 6,
    name: 'PureAir Go',
    price: 44.99,
    originalPrice: 79.99,
    category: 'Home',
    badge: 'Staff Pick',
    description: 'Compact HEPA air purifier for desks, cars, and small rooms.',
    features: ['True HEPA filter', 'Whisper quiet', 'Night mode', 'USB powered'],
    emoji: '🌿',
    gradient: 'linear-gradient(135deg, #96e6a1 0%, #d4fc79 100%)',
    rating: 4.7,
    reviews: 1834,
  },
  {
    id: 7,
    name: 'GlowRing Light',
    price: 19.99,
    originalPrice: 39.99,
    category: 'Tech',
    badge: 'Flash Sale',
    description: '10" RGB ring light with tripod. Perfect for content creators.',
    features: ['10 brightness levels', 'RGB modes', 'Phone holder', 'Remote control'],
    emoji: '💫',
    gradient: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
    rating: 4.5,
    reviews: 4523,
  },
  {
    id: 8,
    name: 'NeatBottle 2.0',
    price: 27.99,
    originalPrice: 45.99,
    category: 'Lifestyle',
    badge: 'Exclusive',
    description: 'Self-cleaning water bottle with UV purification and temp display.',
    features: ['UV purification', 'Temp display', 'Self-cleaning', '17oz capacity'],
    emoji: '💧',
    gradient: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
    rating: 4.9,
    reviews: 3567,
  },
  {
    id: 9,
    name: 'SonicPods X',
    price: 42.99,
    originalPrice: 79.99,
    category: 'Tech',
    badge: 'Best Seller',
    description: 'True wireless earbuds with ANC, 36hr battery, and studio-grade sound.',
    features: ['Active noise cancelling', '36hr battery', 'IPX5 waterproof', 'Touch controls'],
    emoji: '🎧',
    gradient: 'linear-gradient(135deg, #0c3483 0%, #a2b6df 100%)',
    rating: 4.8,
    reviews: 5621,
  },
  {
    id: 10,
    name: 'LunaGlow Strip',
    price: 16.99,
    originalPrice: 34.99,
    category: 'Home',
    badge: 'Trending',
    description: '32ft smart LED strip with music sync. Transform any space instantly.',
    features: ['Music reactive', 'App control', '32ft length', 'Cuttable design'],
    emoji: '🌈',
    gradient: 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
    rating: 4.6,
    reviews: 2893,
  },
  {
    id: 11,
    name: 'FrostMug Pro',
    price: 22.99,
    originalPrice: 39.99,
    category: 'Kitchen',
    badge: 'New',
    description: 'Self-cooling mug that keeps your drink ice cold for 6 hours. No ice needed.',
    features: ['6hr cold retention', 'Double-wall vacuum', 'Condensation-free', 'Dishwasher safe'],
    emoji: '🧊',
    gradient: 'linear-gradient(135deg, #a1c4fd 0%, #c2e9fb 100%)',
    rating: 4.7,
    reviews: 1245,
  },
  {
    id: 12,
    name: 'ZenMat Ultra',
    price: 54.99,
    originalPrice: 99.99,
    category: 'Lifestyle',
    badge: 'Hot Deal',
    description: 'Heated massage mat with 10 vibration modes. Your personal masseuse.',
    features: ['10 vibration modes', 'Heating function', 'Auto shut-off', 'Foldable'],
    emoji: '🧘',
    gradient: 'linear-gradient(135deg, #f6d365 0%, #fda085 100%)',
    rating: 4.9,
    reviews: 1567,
  },
  {
    id: 13,
    name: 'PixelFrame 8K',
    price: 59.99,
    originalPrice: 109.99,
    category: 'Home',
    badge: 'Exclusive',
    description: 'Digital photo frame with WiFi. Share memories from anywhere in the world.',
    features: ['8K display', 'WiFi connected', 'Cloud storage', 'Motion sensor'],
    emoji: '🖼️',
    gradient: 'linear-gradient(135deg, #fccb90 0%, #d57eeb 100%)',
    rating: 4.8,
    reviews: 987,
  },
  {
    id: 14,
    name: 'DeskOrbit Mini',
    price: 18.99,
    originalPrice: 32.99,
    category: 'Office',
    badge: 'Popular',
    description: 'Magnetic desk toy that defies gravity. The ultimate focus fidget.',
    features: ['Magnetic levitation', 'Silent spin', 'Desk decoration', 'Stress relief'],
    emoji: '🪐',
    gradient: 'linear-gradient(135deg, #5ee7df 0%, #b490ca 100%)',
    rating: 4.4,
    reviews: 3421,
  },
  {
    id: 15,
    name: 'NightOwl Mask',
    price: 31.99,
    originalPrice: 54.99,
    category: 'Bedroom',
    badge: 'Staff Pick',
    description: 'Smart sleep mask with built-in speakers and light therapy wake-up.',
    features: ['Bluetooth speakers', 'Light therapy', '100% blackout', 'Memory foam'],
    emoji: '🌙',
    gradient: 'linear-gradient(135deg, #2b5876 0%, #4e4376 100%)',
    rating: 4.7,
    reviews: 2156,
  },
  {
    id: 16,
    name: 'SwiftCharge Pad',
    price: 23.99,
    originalPrice: 44.99,
    category: 'Tech',
    badge: 'Flash Sale',
    description: '3-in-1 wireless charger for phone, watch, and earbuds. One pad rules all.',
    features: ['15W fast charge', '3 devices at once', 'LED indicator', 'Anti-slip base'],
    emoji: '⚡',
    gradient: 'linear-gradient(135deg, #f83600 0%, #f9d423 100%)',
    rating: 4.6,
    reviews: 4102,
  },
]

// ─── Reviews ─────────────────────────────────────────────────────────────────

export const REVIEWS = [
  { name: 'Sarah M.', location: 'Los Angeles, CA', text: 'Obsessed with the AuraLamp! My room looks like a vibe now. Already ordered two more for friends.', rating: 5, avatar: 'S', product: 'AuraLamp Pro' },
  { name: 'Jake R.', location: 'Austin, TX', text: 'ZenBrew is a game-changer for road trips. Coffee snobs will love this thing.', rating: 5, avatar: 'J', product: 'ZenBrew Portable' },
  { name: 'Priya K.', location: 'Toronto, ON', text: 'Shipping was super fast. Everything came well-packaged. Legit impressed.', rating: 5, avatar: 'P', product: 'FlexDesk Stand' },
  { name: 'Marcus T.', location: 'London, UK', text: 'The CloudRest pillow fixed my neck pain. Not even kidding, I sleep like a baby now.', rating: 5, avatar: 'M', product: 'CloudRest Pillow' },
  { name: 'Emily L.', location: 'Sydney, AU', text: 'Love the curation. Every product feels premium but the prices are insane.', rating: 4, avatar: 'E', product: 'NeatBottle 2.0' },
  { name: 'David W.', location: 'Chicago, IL', text: 'FlexDesk Stand is SOLID. Looks way more expensive than it is. 10/10.', rating: 5, avatar: 'D', product: 'FlexDesk Stand' },
  { name: 'Aisha B.', location: 'Dubai, UAE', text: 'NeatBottle is genius. The UV cleaning feature actually works. Future is now.', rating: 5, avatar: 'A', product: 'NeatBottle 2.0' },
  { name: 'Chris N.', location: 'Berlin, DE', text: 'GlowRing leveled up my Zoom calls. Coworkers think I got a studio setup.', rating: 5, avatar: 'C', product: 'GlowRing Light' },
  { name: 'Luna T.', location: 'Seoul, KR', text: 'SonicPods X are better than AirPods. There, I said it. The ANC is insane.', rating: 5, avatar: 'L', product: 'SonicPods X' },
  { name: 'Rico V.', location: 'Miami, FL', text: 'LunaGlow Strip made my gaming setup go viral on TikTok. Enough said.', rating: 5, avatar: 'R', product: 'LunaGlow Strip' },
  { name: 'Mei W.', location: 'Singapore', text: 'SwiftCharge Pad replaced 3 chargers on my nightstand. So clean now.', rating: 4, avatar: 'M', product: 'SwiftCharge Pad' },
  { name: 'Omar H.', location: 'Cairo, EG', text: 'NightOwl Mask + CloudRest Pillow combo = best sleep of my life. Thank you.', rating: 5, avatar: 'O', product: 'NightOwl Mask' },
]

// ─── Features ────────────────────────────────────────────────────────────────

export const FEATURES = [
  { icon: '🚀', title: 'Lightning Shipping', desc: 'Most orders delivered in 5-12 business days worldwide. Real-time tracking on every order.', stat: '5-12 days' },
  { icon: '🔒', title: 'Fort Knox Checkout', desc: 'Military-grade SSL encryption. Apple Pay, Google Pay, and all major cards accepted.', stat: '256-bit' },
  { icon: '↩️', title: '30-Day Returns', desc: "Changed your mind? Full refund, zero questions. We even cover return shipping.", stat: '100% free' },
  { icon: '💎', title: 'Curated Quality', desc: 'Every single product is hand-tested by our team of 12 before it makes the cut.', stat: '< 3% pass' },
  { icon: '🌍', title: 'Global Community', desc: 'Join 50,000+ happy customers in 45+ countries. We ship almost everywhere.', stat: '45+ countries' },
  { icon: '💬', title: '24/7 Support', desc: "Real humans, real fast. Average response time under 2 hours, day or night.", stat: '< 2hr reply' },
]

// ─── FAQ ─────────────────────────────────────────────────────────────────────

export const FAQ_ITEMS = [
  { q: 'How long does shipping take?', a: 'Most orders ship within 24-48 hours and arrive in 5-12 business days depending on your location. All orders include free tracking so you can follow your package every step of the way.' },
  { q: 'What is your return policy?', a: "We offer a hassle-free 30-day return policy on all products. If you're not completely satisfied, just reach out to our support team and we'll arrange a full refund. We even cover return shipping costs." },
  { q: 'Are your products authentic?', a: "Absolutely. Every product in our catalog is sourced directly from verified manufacturers and undergoes our rigorous 12-point quality check. We test every product ourselves before listing it." },
  { q: 'Do you ship internationally?', a: 'Yes! We ship to 45+ countries worldwide. International shipping typically takes 7-15 business days. Customs fees, if applicable, are the responsibility of the customer.' },
  { q: 'How do I track my order?', a: "Once your order ships, you'll receive an email with a tracking number and link. You can also track your order anytime by visiting our website and entering your order number." },
  { q: 'Can I cancel or modify my order?', a: 'You can cancel or modify your order within 2 hours of placing it. After that, orders enter our fulfillment pipeline. Contact our 24/7 support team and we\'ll do our best to accommodate changes.' },
  { q: 'What payment methods do you accept?', a: 'We accept all major credit/debit cards (Visa, Mastercard, Amex), Apple Pay, Google Pay, PayPal, and Shop Pay. All transactions are secured with 256-bit SSL encryption.' },
  { q: 'Do you offer bulk/wholesale pricing?', a: 'Yes! For orders of 10+ units, we offer tiered wholesale pricing. Contact our business team at wholesale@neatnesco.com for a custom quote.' },
]

// ─── Categories ──────────────────────────────────────────────────────────────

export const CATEGORIES = ['All', 'Home', 'Tech', 'Kitchen', 'Bedroom', 'Office', 'Lifestyle']

// ─── Brand Partners ──────────────────────────────────────────────────────────

export const BRANDS = [
  'TechCrunch', 'Wired', 'The Verge', 'Mashable', 'CNET', 'Forbes', 'Business Insider', 'Product Hunt',
]

// ─── Timeline ────────────────────────────────────────────────────────────────

export const TIMELINE = [
  { year: '2023', title: 'The Spark', desc: 'Two friends tired of overpaying for trending products decided to do something about it.' },
  { year: '2024', title: 'First 1,000', desc: 'Launched with 20 products. Hit 1,000 customers in our first month. The community was born.' },
  { year: '2025', title: 'Going Global', desc: 'Expanded to 45+ countries. Crossed 50,000 happy customers and 150+ curated products.' },
  { year: '2026', title: "What's Next", desc: "Building the world's most trusted curation platform. NeatNesCo Labs coming soon." },
]
